version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: event-booking-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_booking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - event-booking-network

  redis:
    image: redis:7-alpine
    container_name: event-booking-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - event-booking-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: event-booking-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - event-booking-network

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  event-booking-network:
    driver: bridge
