image:
  repo: ghcr.io/cyprus7/event-seat-booking
  tag: 28368da2b7577abb5cd2ed502c47c66d057f9444
  repository: ghcr.io/cyprus7/event-seat-booking
host: seats.test.chernov.us
ingress:
  enabled: true
  className: nginx
frontend:
  replicas: 2
backend:
  replicas: 2
  extraEnv:
    - name: ENABLE_SWAGGER
      value: 'true'
imagePullSecrets: []
imagePullPolicy: IfNotPresent
