image:
  repo: ghcr.io/cyprus7/event-seat-booking
  tag: 25ca400a233f7500deb0e4d3b1771ba3f6482ec2
  repository: ghcr.io/cyprus7/event-seat-booking
host: seats.test.chernov.us
ingress:
  enabled: true
  className: nginx
frontend:
  replicas: 2
backend:
  replicas: 2
  extraEnv:
    - name: ENABLE_SWAGGER
      value: 'true'
imagePullSecrets: []
imagePullPolicy: IfNotPresent
