image:
  repo: ghcr.io/cyprus7/event-seat-booking
  tag: 08c86ffc6405e74bb1239fc89263d1bcfee031f0
  repository: ghcr.io/cyprus7/event-seat-booking
host: seats.test.chernov.us
ingress:
  enabled: true
  className: nginx
frontend:
  replicas: 2
backend:
  replicas: 2
  extraEnv:
    - name: ENABLE_SWAGGER
      value: 'true'
imagePullSecrets: []
imagePullPolicy: IfNotPresent
