apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "event-seat-booking.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: {{ include "event-seat-booking.name" . }}-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "event-seat-booking.name" . }}-backend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "event-seat-booking.name" . }}-backend
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: backend
          image: {{ printf "%s/backend:%s" .Values.image.repo .Values.image.tag }}
          ports:
            - containerPort: 3001
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_URL
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_URL
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: BOT_TOKEN
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
{{- with .Values.backend.extraEnv }}
{{ toYaml . | indent 12 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "event-seat-booking.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: {{ include "event-seat-booking.name" . }}-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: {{ include "event-seat-booking.name" . }}-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: 3001
